### ISSUE TITLE
it workin

### ISSUE THREAD

**Issue by walruzperil** [alexandrvicente/hamiyoca#1]
Hello, your script working?

**Comment by walruzperil** [comment]
i start on my server. but it not working have some error in WM tools like:
GET http://mysite.com/echo/info/ 404 (Not Found)
u._start @ sockjs.min.js:27
(anonymous) @ sockjs.min.js:27
work-manager.js:183 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at y.sock.onclose (work-manager.js:183)
    at y.d.dispatchEvent (sockjs.min.js:27)
    at sockjs.min.js:27

Can you help?

**Comment by alexandrvicente** [comment]
This project is currently unmaintained but it seems to be working on the Heroku demo. That said, mysite.com does not seem to support anything beyond static sites and CGI, so it won't be able to run this project.
